name: maas
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - audioread
  - cudatoolkit=10.1
  - ffmpeg
  - lame
  - librosa=0.9.2
  - libsndfile
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - numba
  - numpy
  - unidecode
  - inflect
  - numpy-base
  - pip
  - protobuf=3.20.1
  - pysocks=1.7.1
  - pysoundfile
  - python=3.7.13
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.7.0
  - pywavelets=1.3.0
  - pyyaml=6.0
  - readline
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tensorboardx=2.2
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - torchaudio=0.7.0
  - torchvision=0.8.0
  - tqdm
  - urllib3
  - wheel
  - yaml=0.2.5
  - pip:
    - appnope==0.1.3
    - backcall==0.2.0
    - cython==0.29.30
    - dataclasses==0.6
    - future==0.18.2
    - greenlet==1.1.2
    - ipdb
    - ipython
    - jedi==0.18.1
    - matplotlib-inline==0.1.3
    - msgpack==1.0.4
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.30
    - ptyprocess==0.7.0
    - pygments==2.12.0
    - pysptk
    - git+https://github.com/fbcotter/pytorch_wavelets.git
    - sox
    - toml==0.10.2
    - traitlets==5.3.0
    - wcwidth==0.2.5
    - bitstring==3.1.6
    - --find-links https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
    - ttsfrd
